server:
  port: 8086

#加载日志配置文件
logging:
  level:
    root: info
    com:
      pangu:
        crawler: DEBUG

pangu:
  servername: 
  sb: 
    action: false
  cookie:
    forceOverrideKeys: JSESSIONID
  cache:
    http:
      host: http://124.205.255.18:48590
browser:
  driver:
    chrome-path: D:/chromedriver.exe
spring:
  data: #mongdb数据库配置R
    mongodb:
      primary:
        #      uri: mongodb://db_aictech:Zkyl#20200302@60.205.201.117:27017/db_aictech
        uri: mongodb://aictech:aictech#2020@10.10.53.20:27017,10.10.53.21:27017,10.10.53.22:27017/db_aictech
        enabled: true
      secondary:
        uri: mongodb://db_transfer:Tran#2020@10.10.53.20:27017,10.10.53.21:27017,10.10.53.22:27017/db_transfer?replicaSet=scnebula
        enabled: true

  redis:
    host: 47.94.21.126
    port: 19091
    password: Kyks&1230KLS01

#  freemarker:
#    template-loader-path: classpath:/
#    suffix: .html
#  mvc:
#    view:
#      prefix: /
#      suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5  #LEGACYHTML5
    check-template: true
    servlet:
     content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix:
      classpath:  /templates #classpath:/static/ #,classpath:/templates
    suffix: .html

    resources:
      static-locations: classpath:/templates,classpath:/static