server:
  port: 8086
global:
  storageType: mongodb
#加载日志配置文件
logging:
  level:
    root: INFO
    com:
      pangu:
        crawler: INFO

pangu:
  servername: fwq
  sb:
    action: false
  cookie:
    forceOverrideKeys: JSESSIONID
  cache:
    http:
      host: http://124.205.255.18:48590

spring:
  data: #mongdb数据库配置
    mongodb:
      primary:
        uri: mongodb://aictech:aictech#2020@10.10.53.20:27017,10.10.53.21:27017,10.10.53.22:27017/db_aictech
        enabled: true
      secondary:
        uri: mongodb://transfer:Tax#20200115@10.10.53.63:27017/db_transfer
        enabled: true
  redis:
    host: 10.10.53.13
    port: 16379
    password: Redis@2018!
  freemarker:
    template-loader-path: classpath:/help/
    settings:
      classic_compatible: true
  servlet:
    multipart:
      enabled:true
      max-file-size:30MB
      max-request-size:100MB
browser:
  driver:
    chrome-path: C:/crawler/drivers/chromedriver.exe
#file:
#  staticAccessPath:/upload/**
#  uploadFolder:upload/
servlet:
  multipart:
    max-file-size: 10MB
    enabled: true
serversaveaddr: C:/file